apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: aws-environment-provision
  title: AWS Environment Destroy
  description:  Destroys a cloud environment on AWS
spec:
  owner: guests
  type: Environment
  parameters:
    - title: AWS Workload Account
      required:
        - account
      properties:
        account:
          title: AWS Account
          type: string
          description: AWS Account to destroy
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - System
            defaultKind: System
  steps:
    - id: fetchEnvironment
      name: Fetch Environment
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.account }}
    - id: create-mr
      name: Destroy environment MR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=aws_environments&owner=tamer84
        title: Backstage destroy environment
        description: Destroy
        branchName: destroy_${{ steps['fetchEnvironment'].output.entity.metadata.environment }}
        sourcePath: .
        targetPath: .
  output:
    links:
      - title: Merge request
        description: Link to MR which needs to be approved to trigger the destruction process.
        icon: url
        url: ${{ steps['create-mr'].output.remoteUrl }}
